### ISSUE TITLE
Helm push returns a 401, but curl and helm search/fetch work

### ISSUE THREAD

**Issue by phsteve** [chartmuseum/helm-push#11]
We have a Chartmuseum instance running in our Kubernetes cluster (deployed via the helm chart `chartmuseum-1.6.0`) and for some reason I'm getting a `Error: 401: unauthorized` with `helm push chart_name repo_name`. I've added the repo via `helm repo add --username correct_username --password correct_password repo_name https://chartmuseum.somedomain.com`. I can successfully do `helm search repo_name` and `helm fetch repo_name/chart_name`, so the credentials seem to work unless I try to `helm push`. I can also successfully upload charts with `curl --data-binary "@chart_name-1.0.0.tar.gz" https://chartmuseum.somedomain.com/api/charts -u correct_username:correct_password`.

Any idea why `helm push chart_name repo_name` would give me a 401 or any further steps I could take to debug this?

**Comment by phsteve** [comment]
If it's helpful I don't have any helm-specific environment variables set (like `HELM_REPO_ACCESS_TOKEN`/`_PASSWORD`/`_USERNAME`) and it still gives a 401 even if I pass `-u correct_username -p correct_password` to `helm push`.

**Comment by jdolitsky** [comment]
@phsteve this is strange. Can you try pushing direct to URL?

```
helm push mychart-0.3.2.tgz https://correct_username:correct_password@chartmuseum.somedomain.com
```

**Comment by phsteve** [comment]
@jdolitsky I tried and got `Error: no repo named "https://correct_username:correct_password@chartmuseum.somedomain.com" found -- do I need to somehow specify that it's a URL and not a repo name?

**Comment by jdolitsky** [comment]
@phsteve You must be using older version of the plugin (<0.5.0). Can you reinstall and retry?

```
helm plugin remove push
helm plugin install https://github.com/chartmuseum/helm-push
```

**Comment by phsteve** [comment]
Ah you're right, I was on 0.4.0. With 0.5.0 I still get the 401 pushing direct to the URL...

**Comment by phsteve** [comment]
We figured out the issue -- I had a file at `~/.cfconfig` with credentials for a different Chartmuseum instance that was overriding the credentials in `~/.helm/repository/repositories.yaml`. Renaming that file to `~/.cfconfig.bak` fixed the issue.

Thanks again for your assistance in debugging this @jdolitsky!

**Comment by jdolitsky** [comment]
Yep! Glad we figured it out. The docs should reflect something about that file, will leave this open until that is added.

**Comment by jdolitsky** [comment]
@phsteve added some notes on this to readme. closing

**Comment by hoozecn** [comment]
> We figured out the issue -- I had a file at `~/.cfconfig` with credentials for a different Chartmuseum instance that was overriding the credentials in `~/.helm/repository/repositories.yaml`. Renaming that file to `~/.cfconfig.bak` fixed the issue.
> 
> Thanks again for your assistance in debugging this @jdolitsky!

Hey man. Thanks for the solution! BTW, do you know why the ~/.cfconfig effected helm? it's the cfg file of codefresh, no?
