### ISSUE TITLE
can not push directory

### ISSUE THREAD

**Issue by csrlsm** [chartmuseum/helm-push#125]
I push new chart to my private harbor registry，it return "Error: cannot push directory, must provide chart archive (.tgz)"
here is my logs：
$ helm push nginx/ oci://harbor.xxx.com/chartrepo/project
Error: cannot push directory, must provide chart archive (.tgz)

and when i use https，it return "Error: scheme "https" not supported"
$ helm push nginx/ https//harbor.xxx.com/chartrepo/project
Error: scheme "https" not supported

helm version: v3.71
helm push version: 0.10.1
harbor version: v2.3.4

**Comment by ebuildy** [comment]
well, ``helm push`` will not call this plugin!

use ``helm cm-push``

**Comment by thanhtai9606** [comment]
I think you should use a bash script shell like this
`#!/bin/bash
SEARCH_DIR="./stable/"
IGNORE_FILE="index.yaml"
REPOSITORY="becamex"
for entry in "$SEARCH_DIR"/*
do
  if [[ "$entry" != *"$IGNORE_FILE"* ]]; then 
      helm cm-push $entry $REPOSITORY
  fi
done
`

**Comment by csrlsm** [comment]
> well, `helm push` will not call this plugin!
> 
> use `helm cm-push`

it works with helm cm-push. thx
