### ISSUE TITLE
404: not found plugin "push" exited with error

### ISSUE THREAD

**Issue by billyteves** [chartmuseum/helm-push#13]
So I deployed chartmuseum on my kubernetes. I have set it up to use my aws access key and secret key. I have this endpoint http://testhelm.test.com and I added this repo in my ec2 instance. I tried pushing my sample chart package using the push plugin:

`helm push helloworld-0.1.6.tgz testhelm --context-path=/prod `

Pushing helloworld-0.1.6.tgz to testhelm...
Error: 404: not found
Error: plugin "push" exited with error

**testhelm is the name of my helm repo

Any advice on this?

**Comment by jdolitsky** [comment]
@billyteves I can see 2 potential issues:

- `--context-path=/prod` should only be used if chartmuseum is using the same context path
- By default the helm chart has `DISABLE_API: true`. This must be set to `false` or all `/api` routes will 404

**Comment by agolomoodysaada** [comment]
@billyteves that resolved it for me. Thank you!

**Comment by JokerDevops** [comment]
hi,How was the problem finally solved?

**Comment by JokerDevops** [comment]
Where to set DISABLE_API: true?

**Comment by JokerDevops** [comment]
@jdolitsky

**Comment by jdolitsky** [comment]
@JokerDevops - this is env var needed in environment in which you run ChartMuseum

**Comment by JokerDevops** [comment]
ok,thank you !

**Comment by darvinueza** [comment]
No funciona!
