### ISSUE TITLE
Can't install v0.10.2 on MBP 14, Silicon

### ISSUE THREAD

**Issue by IlqarJamal** [chartmuseum/helm-push#131]
Here is short output from installation steps

```
helm plugin install https://github.com/chartmuseum/helm-push
Downloading and installing helm-push v0.10.2 ...
Failed to detect target architecture
Error: plugin install hook for "cm-push" exited with error
```

Version 0.10.1 installed successfully.

**Comment by jdolitsky** [comment]
cc @volker-raschek - possibly related to https://github.com/chartmuseum/helm-push/pull/130 ?

**Comment by volker-raschek** [comment]
Hi @jdolitsky, 
yes, the message indicates that `uname -m` does not match any of the architectures. 

https://github.com/chartmuseum/helm-push/blob/main/scripts/install_plugin.sh#L15

@IlqarJamal, I would be interested to know what is the output of `uname -m` on your system. 

Maybe it would be an option to restore the old behavior by setting the default to amd64.

**Comment by IlqarMammadovPB** [comment]
> uname -m

Result is:

arm64

**Comment by IlqarMammadovPB** [comment]
One comment: i was able to successfully install 0.10.1 version and it works fine on same machine.

**Comment by volker-raschek** [comment]
HI @IlqarMammadovPB, 
yes you was able to install the plugin, but you installed a binary which not match to your systems architecture. The release 0.10.1 does not include a binary for arm64 architectures.

**Comment by IlqarMammadovPB** [comment]
> HI @IlqarMammadovPB, yes you was able to install the plugin, but you installed a binary which not match to your systems architecture. The release 0.10.1 does not include a binary for arm64 architectures.

You mean release 0.10.2?

**Comment by volker-raschek** [comment]
No, I mean 0.10.1 or can you find a compiled binary for arm64 architectures in [release 0.10.1](https://github.com/chartmuseum/helm-push/releases/tag/v0.10.1) :smile:

**Comment by IlqarMammadovPB** [comment]
> No, I mean 0.10.1 or can you find a compiled binary for arm64 architectures in [release 0.10.1](https://github.com/chartmuseum/helm-push/releases/tag/v0.10.1) 😄

Ok, let me check)

**Comment by volker-raschek** [comment]
@IlqarMammadovPB, it should not works. Please try again
