### ISSUE TITLE
helm plugin install unable to specify version？

### ISSUE THREAD

**Issue by allenjol** [chartmuseum/helm-push#146]
`helm plugin install https://github.com/chartmuseum/helm-push` command to install helm push plugin unable to specify version？

when i was use this command line to install my helm push plugin in my Dockerfile,after a few months, i had to add something to my Dockerfile.

Therefore, after the helm plugin install command is executed again, the latest Helm push plugin is installed, resulting in the failure of the original helm push mode, which needs to be changed to helm cm-push mode.

Or can I download the Centos7 helmpush binary without helm Plugin install, place it in /usr/local/bin/ on the system and use helmpush instead of helm cm-push?

**Comment by Crash-1** [comment]
Hi @allenjol,

Try this one:

`helm plugin install https://github.com/chartmuseum/helm-push.git --version 0.9.0`

Version 0.9.0 is the last version that supported `helm push`

**Comment by allenjol** [comment]
@Crash-1 Thanks for you reply.Before that, Ive try to use `helm cm-push` command to push my chart packages to harbor registry.It doesn't look like much of a change from Helm Push.

**Comment by Crash-1** [comment]
@allenjol 
It's still the same. 
The command had to be renamed due to changes in the original helm command structure starting from version [3.7.0](https://github.com/helm/helm/releases/tag/v3.7.0)

**Comment by allenjol** [comment]
@Crash-1 I got it. Thanks agian!
