### ISSUE TITLE
Error: looks like "XXXXXURLXXX"is not a valid chart repository or cannot be reached: error converting YAML to JSON: yaml:

### ISSUE THREAD

**Issue by sabrisay** [chartmuseum/helm-push#153]
Hi All,

I installed chartmuseum on a POD in EKS cluster. I can access chartmuseum using nginx ingress that points to chartmuseum service.  
However when I am adding chartmuseum as a helm repo I am getting error shown below.
"is not a valid chart repository or cannot be reached: error converting YAML to JSON: yaml: line 7: mapping values are not allowed in this context"

Using kubectl kube-forward svc/<my-chartmuseum-service> 8080:8080 and adding to helm repo works fine.

Can someone help me understand what's happening here?

Much appreciate it!

**Comment by Yagya-omnius** [comment]
you may need to change your CONTEXT_PATH in your chartmuseum (helm chart) , and point similar to into ingress.yaml path as /chartmuseum

**Comment by sabrisay** [comment]
The issue was that SA attached to Chartmuseum was not able to assume role. So connection to storage layer(s3) was not established which resulted in service failure. I could resolve the issue by passing "eks.amazonaws.com/sts-regional-endpoints=true" annotation to Chartmuseum POD.
Thanks
