### ISSUE TITLE
Plugin install is failing with v0.10.3

### ISSUE THREAD

**Issue by iliojunior** [chartmuseum/helm-push#158]
I'm getting the follow error with de v0.10.3:
```
+ helm plugin install https://github.com/chartmuseum/helm-push
Downloading and installing helm-push v0.10.3 ...
https://github.com/chartmuseum/helm-push/releases/download/v0.10.3/helm-push_0.10.3_linux_amd64.tar.gz
tar: invalid magic
tar: short read
Error: plugin install hook for "cm-push" exited with error
```

I didn't find the v0.10.3 in releases section, but on plugin install command it's downloading 0.10.3.
I tried with v0.10.2 and it works as well.

Helm version: 3.2.4

**Comment by gnavalesi-navent** [comment]
Seems to have broken with the last commit. Just an hour ago was still working.
The tag and release have been deleted...

**Comment by morey-tech** [comment]
Is it failing to install because the `v0.10.3` tag was never created after [the plugin metadata was updated](https://github.com/chartmuseum/helm-push/pull/154)?

**Comment by jdolitsky** [comment]
Hi everyone - sorry for the breakage

> Is it failing to install because the v0.10.3 tag was never created

This was the case. Apologies. The tag has now been cut and artifacts released.

Can somebody verify things are working OK?

**Comment by iliojunior** [comment]
Ok, it works.

```
+ helm plugin install --version v0.10.3 https://github.com/chartmuseum/helm-push
Downloading and installing helm-push v0.10.3 ...
https://github.com/chartmuseum/helm-push/releases/download/v0.10.3/helm-push_0.10.3_linux_amd64.tar.gz
Installed plugin: cm-push
```
