### ISSUE TITLE
Error: 404: could not properly parse response JSON: 404 page not found 

### ISSUE THREAD

**Issue by alynlin** [chartmuseum/helm-push#17]
1、helm serve --url=charts

2、helm push ../mychart/ http://127.0.0.1:8879  --context-path=/charts

Error: 404: could not properly parse response JSON: 404 page not found
Error: plugin "push" exited with error

**Comment by jdolitsky** [comment]
@alynlin this plugin does not work w “helm serve”, only with chartmuseum which provides an upload API
