### ISSUE TITLE
cannot push if repo URL contains a path

### ISSUE THREAD

**Issue by gildas** [chartmuseum/helm-push#2]
I set up my Chart Museum behind a proxy. And added it to my helm client:

```console
$ helm repo add acme https://www.acme.com/charts
```

And my nginx on the server side, sends all /charts/ to the proper kubernetes service.

Querying works fine as https://www.acme.com/charts goes to http://pod_url:port/

I also tested with curl and httpie, I can upload a chart fine (following the apis in chartmuseum doc).

```console
$ curl --data-binary "@zzz-0.0.1.tgz" https://www.acme.com/charts/api/charts
```
Later on a `helm fetch acme/zzz` works fine as well.

Now a helm push will fail:

```console
$ helm push mypath/ acme
Error: 404: not found
Error: plugin "push" exited with error
```
On my nginx reverse proxy, I can see the URL path is wrong as it receives: `POST /api/charts/charts` instead of `POST /charts/api/charts`.

I have a feeling the push plugin does not respect the base path of the repo when it was added, or at least messes up the said path.

Or am I missing something?

**Comment by gildas** [comment]
Thanks a lot.

**Comment by jdolitsky** [comment]
np!

**Comment by bcollard** [comment]
This is still the case. 
With curl, I can upload charts to my chartmuseum instance, behind `/chartmuseum` path
With Helm push, I have to add the option `--context-path /chartmuseum`
