### ISSUE TITLE
Helm push not updating the requirements during package

### ISSUE THREAD

**Issue by prabhu43** [chartmuseum/helm-push#28]
### Actual Behaviour:

I created a chart which depends on some other charts. I mentioned those chart details in requirements.yaml. When I did `helm push .` to chart museum, it is packaging only the files that exists in the folder. 

### Expected behavior:
`helm push` should pull the dependency charts mentioned in requirements.yaml & then do package it. 

### Fix:
Currently, `helm push` does `helm package`, instead it should do `helm package --dependency-update` which will update the dependencies in requirements.yaml

**Comment by prabhu43** [comment]
Am working on the fix for this issue.

**Comment by jdolitsky** [comment]
@prabhu43 great thank you!

**Comment by prabhu43** [comment]
@jdolitsky Can you please review this PR?
