### ISSUE TITLE
Ability to push directly to repo URL

### ISSUE THREAD

**Issue by jdolitsky** [chartmuseum/helm-push#3]
Should be able to use a repo URL in place of a repo name, which would not require the repo to be added locally:
```
$ helm push mychart/ https://mychartrepo.com
```

Detection can be based on prefix of "http://" or "https://" in the second positional arg.

Since the repo isnt added with `helm repo add`, we are unable to extract creds from `~/.helm/repository/repositories.yaml`. Authentication mechanism can be determined by env vars, or user/pass on the url (e.g. `https://user:pass@mychartrepo.com`).

**Comment by mattfarina** [comment]
Could this kickoff a login process as part of it?

**Comment by jdolitsky** [comment]
Support added in v0.5.0
