### ISSUE TITLE
helm3 push giving error about not being able to find repositories.yaml

### ISSUE THREAD

**Issue by manojkaithakottil** [chartmuseum/helm-push#37]
I currently installed helm3 along with the helm push plugin by running helm plugin install https://github.com/chartmuseum/helm-push

when i tried to do a helm push <chart> <repo> i get the following error:

Error: Couldn't load repositories file (/root/.local/share/helm/repository/repositories.yaml).

This path doesn't exist with helm3.

If i have helm2 install and i do the upgrade to helm3 i still have to do the following manual steps then helm3 push works fine:

mkdir /root/.local/share/helm/repository/
copy contents from /root/.helm/repository/ to /root/.local/share/helm/repository/

Has anyone else seen this issue and been able to solve it by just having helm3 (and not needing to do the helm2 to helm3 upgrade and doing manual steps)?

**Comment by jdolitsky** [comment]
@manojkaithakottil thanks for opening. There are likely some incompatibilities with Helm 3 that will need to be addressed related to new Helm Home location

**Comment by jdamour98** [comment]
@jdolitsky here's my research/workaround: symlink to the new path, and populate apiVersion (fails otherwise). Tested with docker. The hardcodes paths have to be pulled out and made variables to read from HELM_HOME

`docker run -it --entrypoint sh alpine/helm:3.0.0-rc.2`

```
apk add git
# add example repo
helm repo add istio.io https://storage.googleapis.com/istio-release/releases/1.3.4/charts/
helm plugin install https://github.com/chartmuseum/helm-push
helm push x x
# Errors out

# Workaround:
mkdir /root/.helm
mkdir /root/.helm/repository
ln -s /root/.config/helm/repositories.yaml /root/.helm/repository/repositories.yaml
wget -O /usr/local/bin/yq "https://github.com/mikefarah/yq/releases/download/2.4.1/yq_linux_amd64"
chmod +x /usr/local/bin/yq
yq w -i /root/.helm/repository/repositories.yaml apiVersion v1
```

**Comment by reasonerjt** [comment]
@jdolitsky so looks like there will be no `Helm Home` any more...
https://helm.sh/docs/faq/#xdg-base-directory-support

How about getting rid of the type `helmpath.Home`?

**Comment by ryudice** [comment]
Are there plan to fix the helm 3 issues?

**Comment by smithhannahm** [comment]
Note, that the workaround given by @jdamour98 above, the apiVersion field will be rewritten (and unpopulated) if you `helm repo add` afterwards, so you must redo the `yq` command

**Comment by jdamour98** [comment]
For me, the scripting wasn't worth the reward. My CI/CD now just uses curl:
```
curl --data-binary "@mychart-0.1.0.tgz" http://localhost:8080/api/charts
```

**Comment by jurgenweber** [comment]
I am finding after I push and I attempt to download the chart... the Chart.yaml in the archive is missing the dependencies key in the yaml.

**Comment by jdolitsky** [comment]
Making this plugin work with Helm 3 is top priority for this project. Thank you for your patience

**Comment by jdolitsky** [comment]
Will try to get to this ASAP. If anybody wants to attempt the fix, please let me know

**Comment by wantdrink** [comment]
@jdolitsky  This is actually a good news.

**Comment by hangyan** [comment]
@jdolitsky I can add a fix

**Comment by jdolitsky** [comment]
@hangyan I've started work on a branch here: https://github.com/jdolitsky/helm-push/tree/helm3-support

I dont think a new repo is necessary. We should be able to support both versions - the only real issue is the new Helm home

**Comment by jdolitsky** [comment]
helm-push v0.8.0 has been released with support for both Helm 2 and Helm 3. 

Thank you everyone for your patience!

**Comment by wantdrink** [comment]
Great! Thanks @jdolitsky!

**Comment by jdamour98** [comment]
Thanks @jdolitsky!
