### ISSUE TITLE
Why no new releases?

### ISSUE THREAD

**Issue by karuppiah7890** [chartmuseum/helm-push#42]
It's been quite some time. I do see that there's just one feature from last release - e6e7c3289addbfa5fb7b14e2fd8b28cfdb1089bb - Adding flag to update dependencies before package. Do you think it's worth it to release?

There will also be another update, for this issue - #40 (PR - https://github.com/chartmuseum/helm-push/pull/41)

May be if we see some more features / bug fixes, we can wait for them, and then release sometime? @jdolitsky

**Comment by jdolitsky** [comment]
released 0.8.0!
