### ISSUE TITLE
Update test TLS certs

### ISSUE THREAD

**Issue by jdolitsky** [chartmuseum/helm-push#43]
Unable to run tests since the TLS certs appear to be expired:

```
main_test.go:224: unexpecting error uploading tarball: Post https://127.0.0.1:44907/x/y/z/api/charts: x509: certificate has expired or is not yet valid
```

**Comment by karuppiah7890** [comment]
Yes, I noticed in my local only today morning! Will send a PR for the same! 😄 I just couldn't find any docs or comments regarding the certs. I noticed some two sets of certs I think. I'll need to take a look at the code

**Comment by jdolitsky** [comment]
Fixed in https://github.com/chartmuseum/helm-push/pull/44
