### ISSUE TITLE
Install w/o internet access

### ISSUE THREAD

**Issue by wantdrink** [chartmuseum/helm-push#51]
Hi there,

Is it possible to install helm-push for helm 3.0 without internet access?

I installed it online and checked the plugin folder in /root/.cache/helm/plugins/https-github.com-chartmuseum-helm-push, it's different from unzip from [helm-push_0.8.0_linux_amd64.tar.gz](https://github.com/chartmuseum/helm-push/releases/download/v0.8.0/helm-push_0.8.0_linux_amd64.tar.gz).

├── acceptance_tests
│   ├── 01-helm.robot
│   ├── 02-chartmuseum.robot
│   └── lib
│       ├── ChartMuseum.py
│       ├── common.py
│       ├── HelmPush.py
│       ├── Helm.py
│       └── __init__.py
├── bin
│   └── helmpush
├── cmd
│   └── helmpush
│       ├── main.go
│       └── main_test.go
├── go.mod
├── go.sum
├── LICENSE
├── Makefile
├── pkg
│   ├── chartmuseum
│   │   ├── client.go
│   │   ├── client_test.go
│   │   ├── download.go
│   │   ├── download_test.go
│   │   ├── option.go
│   │   ├── upload.go
│   │   └── upload_test.go
│   └── helm
│       ├── chart.go
│       ├── chart_test.go
│       ├── index.go
│       ├── index_test.go
│       ├── repo.go
│       ├── repo_test.go
│       ├── serverinfo.go
│       └── version.go
├── plugin.yaml
├── README.md
├── releases
│   ├── v0.8.0
│   │   ├── bin
│   │   ├── LICENSE
│   │   └── plugin.yaml
│   └── v0.8.0.tar.gz
├── scripts
│   ├── acceptance.sh
│   ├── install_plugin.sh
│   ├── setup_test_environment.sh
│   └── test.sh
└── testdata
    ├── charts
    │   ├── helm2
    │   │   └── mychart
    │   │       ├── Chart.yaml
    │   │       └── templates
    │   │           └── pod.yaml
    │   └── helm3
    │       └── my-v3-chart
    │           ├── Chart.yaml
    │           ├── templates
    │           │   ├── deployment.yaml
    │           │   ├── _helpers.tpl
    │           │   ├── ingress.yaml
    │           │   ├── NOTES.txt
    │           │   ├── serviceaccount.yaml
    │           │   ├── service.yaml
    │           │   └── tests
    │           │       └── test-connection.yaml
    │           └── values.yaml
    ├── pgp
    │   ├── helm-test-key.pub
    │   ├── helm-test-key.secret
    │   └── NOTE.txt
    └── tls
        ├── ca.crt
        ├── server_ca.crt
        ├── test_cert.crt
        ├── test_key.key
        ├── test_server.crt
        └── test_server.key

**Comment by jdolitsky** [comment]
@wantdrink yes. If you have the release artifact, all you need are the following 2 files:
```
├── bin
│   └── helmpush
└── plugin.yaml
```

Please let me know if this works for you

**Comment by wantdrink** [comment]
@jdolitsky It works. Thanks a lot!
