### ISSUE TITLE
Allow overriding app version during push

### ISSUE THREAD

**Issue by eshepelyuk** [chartmuseum/helm-push#57]
Add `--app-version` flag to `helm push` that can override appVersion for a chart.
Analogous to `helm package --version`

**Comment by sagikazarmark** [comment]
Helm package has an ` --app-version` flag. I think that's what you are really after.

IMHO Helm push shouldn't alter the package after it's created (if the package is signed then it's not possible at all without signing it again)

**Comment by eshepelyuk** [comment]
> Helm package has an --app-version flag. I think that's what you are really after.
@sagikazarmark your assumption is wrong.

`helm package` has both `--version` and `--app-version` flags. It allows you to create `*.tgz` where versions from `Chart.yaml` can be overriden from command line.

From the other side, `helm push` plugin has a push command that is able to call `helm package` _implicitely_.
Idea is that instead of 2 lines of code

    $ helm package ...
    $ helm push ...

Using `helm push` - one could write just  a single line instead. ( This is actually highlighted in [README](https://github.com/chartmuseum/helm-push#pushing-a-directory).

   $ helm push ....

And this plugin will call `helm package` and then pushes `*.tgz` into Chartmuseum.

Unfortunately, `helm push` only has `--version` ( that is passes into `helm package` ), but lacks `--app-version`.
So, this issue is dedicated to adding that flag as well.

**Comment by sagikazarmark** [comment]
I see, thanks for the clarification. I've never used that feature. 😄 

`helm package` has a bunch of options, I wonder if a generic solution would be better than adding flags one by one on demand. Something like `HELM_PACKAGE_OPTS` env var maybe?

But I guess `--version` and `-- app-version` are the most common ones, so it could make sense to add those flags explicitly.

**Comment by eshepelyuk** [comment]
@sagikazarmark yeah, `HELM_PACKAGE_OPTS` sounds reasonable too. 
It would definately help to improve CD flows :)
