### ISSUE TITLE
scripts/install_plugin.sh: 14: [: Linux: unexpected operator

### ISSUE THREAD

**Issue by techadrian** [chartmuseum/helm-push#7]
Hi, 

Trying to deploy on Centos 7 gives :

# helm plugin install https://github.com/chartmuseum/helm-push
Downloading and installing helm-push v0.4.0 ...
scripts/install_plugin.sh: 14: [: Linux: unexpected operator
scripts/install_plugin.sh: 16: [: Linux: unexpected operator
https://github.com/chartmuseum/helm-push/releases/download/v0.4.0/helm-push_0.4.0_windows_amd64.tar.gz

Checked the scripts/install_plugin.sh script and saw that you are using == to compare strings.
Using = instead of == fixes the issue. 

Based on my experience, == will not work on every shell, and = should be the way to go. 

Keep up the good work!

**Comment by jdolitsky** [comment]
@techadrian thanks! I've made your suggested change on master. Can you try the "helm plugin install" again and verify it works on your end?

**Comment by techadrian** [comment]
@jdolitsky : Works  like a charm. Thanks.
