### ISSUE TITLE
how to support more arch ，such as mips64le

### ISSUE THREAD

**Issue by duchuanLX** [chartmuseum/helm-push#72]
build_linux: export GOARCH=$(GOARCH)
build_linux: export CGO_ENABLED=0
build_linux: export GO111MODULE=on
build_linux: export GOPROXY=https://gocenter.io
build_linux:
        @GOOS=linux go build -v --ldflags="-w -X main.Version=$(VERSION) -X main.Revision=$(REVISION)" \
                -o bin/linux/amd64/helmpush cmd/helmpush/main.go  # linux

link_linux:
        @cp bin/linux/amd64/helmpush ./bin/helmpush

**Comment by duchuanLX** [comment]
@technosophos What should I do to support mips

**Comment by technosophos** [comment]
Sorry... I am not a core maintainer on this project, so I don't know.

**Comment by duchuanLX** [comment]
@Josh Dolitsky @Matt Butcher What should I do to support mips

**Comment by duchuanLX** [comment]
already support

**Comment by duchuanLX** [comment]
already support

**Comment by duchuanLX** [comment]
close
