### ISSUE TITLE
it's look like don't support sonatype nexus ?

### ISSUE THREAD

**Issue by niwota** [chartmuseum/helm-push#74]
Error: 405: could not properly parse response JSON: 
<!DOCTYPE html>
<html lang="en">
<head>
  <title>405 - Nexus Repository Manager</title>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>

**Comment by philomory** [comment]
Nexus has it's own community-maintained Helm plugin: https://github.com/sonatype-nexus-community/helm-nexus-push
