### ISSUE TITLE
.cfconfig should not affect non codefresh behaviour

### ISSUE THREAD

**Issue by i5okie** [chartmuseum/helm-push#81]
Hello,

I have codefresh cli installed. We use Harbor for docker image and helm chart repo.

as per readme: https://github.com/chartmuseum/helm-push#token-config-file-cfconfig
`~/.cfconfig` directly affects how `helm push` command works.

This is indeed convenient when pushing to Codefresh repo.

However, when I need to push to Harbor with basic auth. ~/.cfconfig context takes precedent and overwrites the `--username` and  `--password` flags both when the repo is added, and when used along with `helm push` command.

This means that helm push sends request to harbor with bearer token header, which results in ```Error: 401: could not properly parse response JSON: {"errors":[{"code":"UNAUTHORIZED","message":"UnAuthorized"}]}``` error.

Commenting out ~/.cfconfig every time I need to push a chart to a private repo (not codefresh) seems unnecessary and silly.

Please change the behavior so that .cfconfig does not take precedence over helm's repo configuration and --username/--password flags.

**Comment by jdolitsky** [comment]
@i5okie yes, I agree. Would you be willing to submit a PR for this?

**Comment by i5okie** [comment]
@jdolitsky  done: https://github.com/chartmuseum/helm-push/pull/86
