### ISSUE TITLE
[Question] Are we able to use this with jfrog?

### ISSUE THREAD

**Issue by dwardu89** [chartmuseum/helm-push#9]
I'm using JFrog for chartmuseum. 
Ive tried setting the following
`HELM_REPO_AUTH_HEADER="X-JFrog-Art-Api"`
`HELM_REPO_ACCESS_TOKEN=<MYAPIKEY>`
then running a `helm push . chartmuseum` however i get back a 404 when ever i try push.
Is there something that i'm missing?

**Comment by jdolitsky** [comment]
@dwardu89 as far as I understand, the JFrog Helm repos are not based on ChartMuseum. Therefore, the API endpoint for uploads may look completely different.

Looks like you need to use the `jfrog rt` command to push your charts:
```
jfrog rt u "*.tgz" helm-local
```

Checkout this post: https://jfrog.com/blog/master-helm-chart-repositories-artifactory/
